apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-python
  labels:
    api: api-python

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      api: api-python
      
  template:
    metadata:
      labels:
        api: api-python
    spec:
      containers:
      - name: api-python
        image: rael18/api-python:v4.2
        imagePullPolicy: IfNotPresent
        envFrom:
         - configMapRef:
             name: api-python-config
        ports:
        - containerPort: 5000

        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 10

      resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "200m"
      
      
