apiVersion: v1
kind: Service
metadata:
  name: api-python-service
spec:
  selector:
    api: api-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
  type: NodePort


  