apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  labels:
    db: mysql


spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql
        image: rael18/mysql-api:v1
        ports:
        - containerPort: 3306
        envFrom:
         - configMapRef:
             name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "200m"
      
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
